version: '3.8'

services:
  mysql:
    container_name: mysql-server
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    command: ['--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./data/mysql:/var/lib/mysql
